### ISSUE TITLE
Release dev branch, as 0.9.0 has many conflicts with laravel and lumen 5.6

### ISSUE THREAD

**Issue by ontehfritz** [FriendsOfOuro/geteventstore-php-core#49]
dev master works, 0.9.0 is basically unusable because the composer packages are outdated

**Comment by dbellettini** [comment]
Sorry, I forgot to push v0.10.0 tag. Furthermore I released the v0.11.0

**Comment by ontehfritz** [comment]
Sweet, Thanks alot I will check out 0.11.0
