### ISSUE TITLE
Allow for custom headers in requests

### ISSUE THREAD

**Issue by fhoutr01** [FriendsOfOuro/geteventstore-php-core#50]
Hi,

I have a feature request caused by/based on a bug in the EventStorm product itself: https://github.com/EventStore/EventStore/issues/1574.

It would be nice if you could set headers in the requests ( such as in `writeToStream` ).

**Situation**
We have a cluster of three nodes. One master and two slaves.
The bug I linked above always sends the header `Transport-Encoding` header as `chunked`.
There's a chance we get an `HTTP 415` error when we write to a stream. Eventstore slaves drop certain headers when they forward their write requests to the master node.
Thus some events get rejected, because they ended up on the slave node. The more slaves we add, the bigger the chance for this to occur. When we write to a stream on the master there is no issue.

**Workaround**
The reporter suggests a workaround by setting the `Content-Length` header. If there is a `Content-Length` header, the `Transport-Encoding` header is not added. The internal redirect works in this case.

This header( `Transport-Encoding` ) is presumably (?) added somewhere outside of your library ( PHP Curl implementation? Curl itself? ). 

I can't find a way to add a request header for the `writeToStream` method from your EventStore class.
My only "clean" solution is to extend your class and overwrite your `writeToStream` method. This until they resolve the original issue, which has been open since March 2018.

**conclusion**
It seems like a neater solution if we could add extra header(s) to the request.

Added my quickfix below. Look for the `Content-Length` line. The length gets recalculated so you can default it to 0.

File:: dbellettini/geteventstore-core/src/EventStore/EventStore.php
```
    public function writeToStream($streamName, WritableToStream $events, $expectedVersion = ExpectedVersion::ANY)
    {
        if ($events instanceof WritableEvent) {
            $events = new WritableEventCollection([$events]);
        }

        $request = new Request(
            'POST',
            $this->getStreamUrl($streamName),
            [
                'ES-ExpectedVersion' => intval($expectedVersion),
                'Content-Type'       => 'application/vnd.eventstore.events+json',
                'Content-Length'     => '0',
            ],
            json_encode($events->toStreamData())
        );
        $this->sendRequest($request);

        $responseStatusCode = $this->getLastResponse()->getStatusCode();

        if (ResponseCode::HTTP_BAD_REQUEST == $responseStatusCode) {
            throw new WrongExpectedVersionException();
        }
    }
```
 An alternative is to set the correct size immediately:

```$request  = $request->withAddedHeader( 'Content-Length', $request->getBody()->getSize() );```

I'm sceptical about this feaure request, as it's an implementation to work around a bug in EventStore. 

Let me know your thoughts. I may be missing something

EDIT: changed some phrasings for clarity.
EDIT: Removed the ** for bold in the code block as it's ignored.

**Comment by dbellettini** [comment]
Hello @fhoutr01 I'll have a look next week

**Comment by dbellettini** [comment]
Hello @fhoutr01, sorry for letting this in my inbox for a month. I thought I could manage it, but it couldn't, I would really appreciate a Pull Request from you if it is still the case

**Comment by fhoutr01** [comment]
Hi @dbellettini ,

Just came back from holiday. I'll try and send a pull request somewhere this week!

**Comment by fhoutr01** [comment]
Created two pull requests.

*headerfix_1*
One just adds the header.

*headerfix_2*
The other adds the header and allows you to specify additional headers ( very basic without a lot of validation ) when calling the writeToStream() function ( union of additional headers and hardcoded headers)
